[python]
# Modules to be brought up by simply running the python processes async
# Leave this empty if no blocks should be started like this
modules_root = '../../nonrelease_dareplane/dp-reaction-time'                                                            # path to the root if the modules

# -------------------- Mockup Streamer ---------------------------------------
[python.modules.dp-reaction-time]                                      # names of a module to be used (folder name)
    type = 'reaction-time'
    port = 8082                                                                 # if no port is provided, a random free port is chosen
    ip = '127.0.0.1'

# -------------------- Controller  -----------------------------------------
[python.modules.dp-lsl-recording]                                     # names of a module to be used (folder name)
    type = 'dataio'
    port = 8084
    ip = '127.0.0.1'


[macros]
[macros.start_streaming]
    name = 'START_paradigm'
    description = 'start streaming'
[macros.start_streaming.default_json]
    block = 1
    fname = 'test_reaction_$<block>'
    date_root = '../'
[macros.start_streaming.cmds]
    # [<target_module>, <PCOMM>, <kwarg_name1 (optional)>, <kwarg_name2 (optional)>]
    com1 = ['dp-lsl-recording', 'UPDATE']
    com2 = ['dp-lsl-recording', 'SELECT_ALL']
    com3 = ['dp-lsl-recording', 'RECORD']
    com4 = ['dp-reaction-time', 'RUN']

[macros.stop_streaming]
    name = 'STOP_paradigm'
    description = 'stop streaming'
[macros.stop_streaming.cmds]
    # [<target_module>, <PCOMM>, <kwarg_name1 (optional)>, <kwarg_name2 (optional)>]
    com1 = ['dp-lsl-recording', 'STOPRECORD']
    # com2 = ['dareplane_spoc_recording', 'SET_SAVE_PATH', 'rec_dir=data_root']
